# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fdc6bcd89987bcd0e1393a36e9799ee166cff1d0c0bf15604cee645c5f5c7863791824b908efb508f8eb176bef5d8034ae4a9bbf8b71130eab658758340f2cd

test:
  secret_key_base: fd1728a12526c9eb0587245adab52e0c4a950ade7bd2c155bd72ab035c3bc260409dc97b91a843913138b80eac2d69ad517d9c3b834ce343a691ddb10bbd3219

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
